modules/models.py
from . import db


class GalleryModel(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    pickled_gallery = db.Column(db.PickleType, nullable=False)

app.py
from modules import app

if __name__ == '__main__':
    app.run(debug=True)

modules/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy


app = Flask(__name__,
            static_url_path='',
            static_folder='../static',
            template_folder='../templates')

app.config.from_object('config.DevelopmentConfig')
db = SQLAlchemy(app)

from .routes import routes
app.register_blueprint(routes, url_prefix='/')

modules/routes.py
from modules.models import GalleryModel
from flask import Blueprint, render_template, request, redirect, url_for, send_file, session, flash
from .api_operations import Gallery, PictureObject, FileTransfer
from threading import Thread
from . import db

routes = Blueprint('routes', __name__)


@routes.route('/')
def home():
    """ Redirects to welcome function """
    return redirect(url_for('routes.welcome'))


@routes.route('/welcome')
def welcome():
    """ Renders welcome template """
    return render_template('welcome.html')


@routes.route('/about')
def about():
    """ Renders about template """
    return render_template('about.html')


@routes.route('/gallery', methods=['POST', 'GET'])
def gallery():
    """
    Redirects to gallery if requested by post method.
    Otherwise renders gallery, with images if one was already created.

    """

    if request.method == 'POST':
        search = request.form['search']
        number_of_images = request.form['search-number']
        return redirect(f'/generate-gallery/{search}/{number_of_images}')

    elif session.get('gallery_id'):
        try:
            unpickled_gallery = FileTransfer.unpickle_gallery()
            return render_template('gallery.html', images=unpickled_gallery.get_picture_objects())
        except:
            return render_template('gallery.html')

    else:
        return render_template('gallery.html')


@routes.route('/generate-gallery/<search>/<int:number_of_images>', methods=['GET'])
def generate_gallery(search, number_of_images):
    """
    Generates gallery using threads in order to reduce time user has to wait for requests.
    Adds gallery id to session variable in order to know which gallery belong to user.

    """

    if request.method == 'GET':
        search.replace('%20', ' ')
        gallery = Gallery([])

        def get_picture(number_of_picture):
            image = PictureObject(number_of_picture, search)
            gallery.add_picture(image)

        threads = []
        for i in range(number_of_images):
            threads.append(Thread(target=get_picture, args=(i,)))
        for thread in threads:
            thread.start()
        for thread in threads:
            thread.join()

        clear_db()
        session['gallery_id'] = FileTransfer.make_gallery_model_object(gallery)
        unpickled_gallery = FileTransfer.unpickle_gallery()

        return render_template('gallery.html', images=unpickled_gallery.get_picture_objects(), number_of_images=number_of_images)


@routes.route('/apply-changes', methods=['POST'])
def apply_changes():
    """
    Applies changes requested by user. Picture index variable makes sure to keep track with
    images id, that changes when picture is deleted.

    """
    if request.method == 'POST':
        gallery = FileTransfer.unpickle_gallery()
        pictures = gallery.get_picture_objects()

        picture_index = -1
        for i in range(len(pictures)):
            picture_index += 1  # this index makes sure delete function does not distrub this loop
            form_number = i + 1  # images on website are indexed 1 number higher
            blur = request.form[f"blur{form_number}"]
            brightness = request.form[f"brightness{form_number}"]
            transpose = request.form.get(f"transpose{form_number}")
            delete = request.form.get(f"delete{form_number}")
            if blur != '':
                pictures[picture_index].change_blur(int(blur))
            if brightness != '':
                pictures[picture_index].change_brightness(
                    float(brightness.replace(',', '.')))
            if transpose is not None:
                pictures[picture_index].transpose()
            if delete is not None:
                gallery.delete_picture(picture_index)
                picture_index -= 1

        clear_db()
        session['gallery_id'] = FileTransfer.make_gallery_model_object(gallery)
        return render_template('gallery.html', images=gallery.get_picture_objects())


@routes.route('/download-gallery', methods=['POST'])
def download_gallery():
    """ Downloads gallery using zipfile and io libraries. """

    if request.method == 'POST':
        try:
            gallery = FileTransfer.unpickle_gallery()
            if gallery.get_picture_objects() == []:
                raise Exception()
            zip_file_bytes_io = gallery.save_gallery()
            return send_file(zip_file_bytes_io, mimetype='application/zip', as_attachment=True, download_name='gallery.zip')
        except:
            flash('There was problem downloading your gallery')
            return redirect('/gallery')


@routes.route('/display-image/<int:id>')
def display_image(id):
    """ Displays larger image in new tab. """
    gallery = FileTransfer.unpickle_gallery()
    image = gallery.get_picture_objects()[id-1].get_bytes_picture()
    return render_template('display_image.html', image=image)


@routes.route('/collage/<int:collage_style_number>', methods=['POST'])
def collage(collage_style_number):
    """ Renders collage from picked images """

    collage_length = {1: 6,
                      2: 9,
                      3: 5,
                      }

    if request.method == 'POST':
        try:
            gallery = FileTransfer.unpickle_gallery()
            pictures = gallery.get_picture_objects()
            acceptable_indexes = [str(index)
                                  for index, image in enumerate(pictures, 1)]
            index_list = request.form[f"collage{collage_style_number}"].split()

            for index in index_list:
                if index not in acceptable_indexes:
                    flash('Indexes of images are not in range!')
                    return render_template('gallery.html', images=gallery.get_picture_objects(), number_of_images=len(pictures))

            if len(index_list) != collage_length[collage_style_number]:
                flash('Wrong number of images!')
                return render_template('gallery.html', images=gallery.get_picture_objects(), number_of_images=len(pictures))

            collage_gallery = Gallery([pictures[int(i)-1] for i in index_list])
            session[f'collage{collage_style_number}_id'] = FileTransfer.make_gallery_model_object(
                collage_gallery)
            return render_template('collage.html', images=collage_gallery.get_picture_objects(), collage_style_number=collage_style_number)

        except:
            flash('There was problem with collage. Make sure to generate gallery first!')
            return redirect('/gallery')


def clear_db():
    """
    Deletes latest model, it is not covering all cases in order to allow multiple users to use application,
    but reduces frequency of clearing database
    """
    if session.get('gallery_id'):
        try:
            GalleryModel.query.filter(
                GalleryModel.id == session['gallery_id']).delete()
            db.session.commit()
        except:
            print('Model does not exist')

templates/about.html
{% extends 'base.html' %}

{% block head %}
<title>OnlineGallery</title>
{% endblock %}

{% block body %}
<div class="welcome-container">
    <div class="text-gradient">
        <div class="welcome-text">
            <h2>
                Gallery allows you to generate a gallery about your topic and make a collage from it.
                <br>
                After the gallery is loaded you can apply 3 different effects or delete the image from the gallery.
                <br>
                To apply these changes, click the button on the left side of the screen.
                <br>
                After applying effects you can select pictures to make collage from this gallery.
                <br>
                To download gallery or collage click button on left side of screen.
                <br>
                This app works best with 100% website size.
            </h2>
        </div>
    </div>

</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" type="image/png" href="/images/favicon.ico" />
    <link rel="stylesheet" href="/css/main.css">
    <link rel="stylesheet" href="/css/collage.css">
    <!-- fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block head %}{% endblock %}
</head>

<body>
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class=flashes>
        {% for message in messages %}
        <div>{{ message }}</div>
        {% endfor %}
    </div>
    {% endif %}
    {% endwith %}

    <nav class="navbar">
        <div class="topnav" id="myTopnav">
            <div class="nav-item">
                <a href="{{url_for('routes.welcome')}}">Home</a>
            </div>
            <div class="nav-item">
                <a href="{{url_for('routes.gallery')}}">Gallery</a>
            </div>
            <div class="nav-item">
                <a href="{{url_for('routes.about')}}">About</a>
            </div>
        </div>
    </nav>

    {% block body %}{% endblock %}

    <footer class="footer">Strona stworzona przez Łukasza Główkę, studenta Politechniki Warszawskiej</footer>
</body>

<script>
    let current_url = document.location;
    document.querySelectorAll(".topnav a").forEach(function (e) {
        if (e.href == current_url) {
            e.classList += " current";
        }
    });
</script>
{% block additional_script %}{% endblock %}

</html>

templates/collage.html
{% extends 'gallery_base.html' %}

{% block content %}
<div class="collage-wrapper1">
    <div id="collage" class="collage{{collage_style_number}}">
        {% for image in images %}
        <figure class="collage_item collage_item{{loop.index}}">
            <img src={{ image.get_bytes_picture() }} class="collage_img" title="Image {{loop.index}}"
                alt="Image {{loop.index}}">
        </figure>
        {% endfor %}
    </div>
</div>
{% endblock %}

{% block download %}
<button onclick="functioncanvas()" id="click" class="download-button">
    <i class="fa fa-download"></i> Download Collage
</button>
{% endblock %}

{% block additional_script %}
<script src="../js/html2canvas.js"></script>
<script>
    function functioncanvas() {
        html2canvas(document.querySelector("#collage")).then(canvas => {
            document.body.appendChild(canvas)
            canvas.id = "canvas"
            var link = document.createElement('a');
            link.download = 'collage.png';
            link.href = document.getElementById('canvas').toDataURL()
            link.click();

        });
    }
</script>
{% endblock %}

templates/display_image.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/png" href="/images/favicon.ico">
    <link rel="stylesheet" href="/css/main.css">
    <title>Document</title>
</head>

<body class="display-image">
    <div class="display-image-wrapper">
        <img class="displayed-image" src={{ image }} />
    </div>
</body>

</html>

templates/gallery.html
{% extends 'gallery_base.html' %}

{% block content %}

<div class="search">
    <form class="search-form" action='/gallery' method='POST'>
        <input id='search' class="search-input" type="text" placeholder="Type what interests you!" name="search"
            autofocus=True required value="">
        <div class="number-of-images-wrapper">
            <input id='number-of-images' class="number-of-images" type="number" min="2" max="15" name="search-number"
                required value="">
            <span class="tooltiptext">Number of images(2-15)</span>
        </div>
        <button class="search-button" type="submit">
            <i class="fa fa-search"></i>
        </button>
        <label class='search-label' for="search">You can type more than one thing, but it has to be separated by
            spaces.</label>
    </form>
</div>
<div class="gallery-wrapper">
    {% if images %}

    <form class="gallery" action='/apply-changes' method='POST'
        title="If apply changes button does not work, your changes are incorrect.">
        <button class="apply-changes">Apply changes</button>
        {% for image in images%}

        <div class="image">
            <a href='/display-image/{{loop.index}}' target="_blank">
                <img src={{ image.get_bytes_picture() }} />
            </a>
            <div class="image-option">
                <input name="blur{{loop.index}}" class="option blur" type="number" placeholder="Blur: from 1 to 10"
                    min="1" max="10">
                <input name="brightness{{loop.index}}" class="option brightness" type="number"
                    placeholder="Increase/decrease brightness" min="0.1" max="2" step="0.1">
                <div class="option transpose-option-wrapper">
                    <input name="transpose{{loop.index}}" class="option transpose" type="checkbox">
                    <span class="tooltiptext">Check to transpose image {{loop.index}}</span>
                </div>
                <div class="option transpose-option-wrapper">
                    <input name="delete{{loop.index}}" class="option transpose" type="checkbox">
                    <span class="tooltiptext">Check to delete image {{loop.index}}</span>
                </div>
            </div>
        </div>
        {% endfor %}

    </form>
    {% else %}

    <div class="gallery">
        {% for i in range(6) %}

        <div class="empty-image">
            <div class="empty-image-text">
                There will be your gallery
            </div>
        </div>
        {% endfor %}

    </div>
    {% endif %}

</div>


{% endblock %}

{% block download %}
<form action='/download-gallery' method='POST'>
    <button class="download-button">
        <i class="fa fa-download"></i> Download
        Gallery
    </button>
</form>
{% endblock %}

templates/gallery_base.html
{% extends 'base.html' %}
{% block head %}

<title>Gallery</title>
{% endblock %}

{% block body %}

<div class="gallery-container">
  <div class="sidenav">
    <div>
      <a><img class="sidenav-collage" src="/images/collage1.png" /></a>
      <form class="collage-form" action='/collage/1' method='POST'>
        <div class='collage-option-get-wrapper'>
          <input name="collage1" class="collage-input" type="text" required value="" title='' placeholder="1 2 3 4 6 5">
          <span class="tooltiptext">Input indexes of images separated by spaces in order you prefer them to be.</span>
        </div>
        <button class="collage-button">
          Send
        </button>
      </form>
    </div>
    <div>
      <a><img class="sidenav-collage" src="/images/collage2.png" /></a>
      <form class="collage-form" action='/collage/2' method='POST'>
        <div class='collage-option-get-wrapper'>
          <input name="collage2" class="collage-input" type="text" required value="" title=''
            placeholder="1 2 3 4 6 5 7 8 9">
          <span class="tooltiptext">Input indexes of images separated by spaces in order you prefer them to be.</span>
        </div>
        <button class="collage-button">
          Send
        </button>
      </form>
    </div>
    <div>
      <a><img class="sidenav-collage" src="/images/collage3.png" /></a>
      <form class="collage-form" action='/collage/3' method='POST' title=''>
        <div class='collage-option-get-wrapper'>
          <input name="collage3" class="collage-input" type="text" required value="" placeholder="2 3 7 1 4">
          <span class="tooltiptext">Input indexes of images separated by spaces in order you prefer them to be.</span>
        </div>
        <button class="collage-button">
          Send
        </button>
      </form>
    </div>
    {% block download %}{% endblock %}

  </div>
  <div class="content-wrapper">
    {% block content %}{% endblock %}
  </div>
</div>

{% endblock %}

{% block additional_script %}{% endblock %}

templates/welcome.html
{% extends 'base.html' %}

{% block head %}
<title>OnlineGallery</title>
{% endblock %}

{% block body %}
<div class="welcome-container">
    <div class="text-gradient">
        <div class="welcome-text">
            <h1>
                Welcome to online gallery.
            </h1>
            <h2>
                Gallery allows you to generate gallery about your topic and make collage from it.
                <br>
                You can go to gallery by clicking on navigation bar above.
            </h2>
        </div>
    </div>

</div>
{% endblock %}